"""
constants for genetic algorithm
P_* - probability
"""

P_MUTATION = 0.8
TOTAL_POPULATION = 300
P_CROSSOVER = 0.8
AMOUNT_TIMELINES_IN_DAY = 14
TIME_FIRST_LESSON_SECOND_SHIFT = 6
COUNT_GENERATIONS = 1000
EXIT_OF_ALGORITHM = 1000
