"""
constants for genetic algorithm
P_* - probability
"""

P_MUTATION = 0.8
TOTAL_POPULATION = 3
P_CROSSOVER = 0.2
AMOUNT_TIMELINES_IN_DAY = 14
TIME_FIRST_LESSON_SECOND_SHIFT = 6
COUNT_GENERATIONS = 100
